"""Add Partido.creado_por_desafio_id

Revision ID: 4a2b01d7b8ff
Revises: 9aa002123d8c
Create Date: 2025-10-19 18:05:42.750136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2b01d7b8ff'
down_revision = '9aa002123d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_jugadores_email'), sqlite_where=sa.text('email IS NOT NULL'))

    with op.batch_alter_table('partido_resultado_propuesto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prp_creado_en'))

    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_por_desafio_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_partidos_creador'))
        batch_op.drop_index(batch_op.f('ix_partidos_estado'))
        batch_op.drop_index(batch_op.f('ix_partidos_resultado_propuesto_en'))
        batch_op.drop_index(batch_op.f('ix_partidos_rival1'))
        batch_op.drop_index(batch_op.f('ix_partidos_rival2'))

    with op.batch_alter_table('torneos_participantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_torneos_participantes_inscripcion_id'), ['inscripcion_id'], unique=False)

    with op.batch_alter_table('torneos_partidos', schema=None) as batch_op:
        batch_op.create_index('ix_torneos_partidos_programado', ['programado_en'], unique=False)
        batch_op.create_index('ix_torneos_partidos_torneo_estado', ['torneo_id', 'estado'], unique=False)
        batch_op.create_unique_constraint('uq_grupo_partido_ab', ['grupo_id', 'participante_a_id', 'participante_b_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torneos_partidos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_grupo_partido_ab', type_='unique')
        batch_op.drop_index('ix_torneos_partidos_torneo_estado')
        batch_op.drop_index('ix_torneos_partidos_programado')

    with op.batch_alter_table('torneos_participantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_torneos_participantes_inscripcion_id'))

    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partidos_rival2'), ['rival2_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_rival1'), ['rival1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_resultado_propuesto_en'), ['resultado_propuesto_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_creador'), ['creador_id'], unique=False)
        batch_op.drop_column('creado_por_desafio_id')

    with op.batch_alter_table('partido_resultado_propuesto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prp_creado_en'), ['creado_en'], unique=False)

    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_jugadores_email'), ['email'], unique=1, sqlite_where=sa.text('email IS NOT NULL'))

    # ### end Alembic commands ###
